
// Parser generated by Maphoon 2024.
// Written by Hans de Nivelle, March 2021-May 2024.
// See the licence that was included with the code.

#include "parser.h"



size_t 
parsing::parser::statesymbol::hash::operator( ) ( const statesymbol& ss ) const
{
   // After some trying, and looking at the distribution in the map,
   // this gives decent results:

   auto s = ss. state;
   auto t = ss. val;
   size_t h = s + 41 * t + t * t; 
   h ^= ( h >> 7 );
   return h;
}

bool
parsing::parser::statesymbol::equal_to::operator( ) ( const statesymbol& ss1,
                                                            const statesymbol& ss2 ) const
{
   return ss1. state == ss2. state && ss1. val == ss2. val;
}


// Definitions of the reduction functions:

auto parsing::parser::body5( ) -> void
{
#line 51 "parsing/grammar.m"
std::cout << "Definition!\n";}

auto parsing::parser::body9( ) -> void
{
#line 60 "parsing/grammar.m"
std::cout << "STRUCT!\n";}



#line 1 "reduce"

void parsing::parser::reduce( parsing::symbolval leftval,
               parsing::symbol::attrtype&& attr, size_t rightsize )
{
   if( debug >= 2 )
   {
      std::cout << "popping " << rightsize << " state(s) and symbol(s) "; 
      std::cout << "from the stack and reducing into " << leftval << "\n";
   }

#if true
   // This works only if symbol has an infotype: 

   std::optional< parsing::symbol::infotype > info;
      // For the first stack entry that has an info, we move it into here. 
      // For later stack entries that have an info, we merge them
      // with the first info. The idea is that info has set semantics. 

   for( auto p = symbolstack. end( ) - rightsize; 
        p != symbolstack. end( ); ++ p ) 
   {
      // If we encounter first defined, we move into info. 
      // 

      if( p -> info. has_value( )) 
      {
         if( info. has_value( ))
            info.value( ). merge( std::move( p -> info.value() ));
         else
            info = std::move( p -> info );
      }
   }
#endif 

   while( rightsize )
   {
      statestack. pop_back( );
      symbolstack. pop_back( );
      -- rightsize; 
   }
  
   // It remains to do the goto: 

   statestack. push_back( shifts. at( { statestack. back( ), leftval } ));

#if true
   symbolstack. emplace_back( leftval, info, std::move( attr ));
#else
   symbolstack. emplace_back( leftval, std::move( attr ));
#endif 
}

#line 1 "parse"

parsing::symbol 
parsing::parser::parse( parsing::symbolval startsym )
{
   if( debug )
      std::cout << "Starting parser:\n";

   if( checkmovable ) 
   {
      if( ! std::is_nothrow_move_constructible<parsing::symbol> :: value )
      {
         std::cout << "class symbol is not nothrow move constructible\n";
         std::cout << "   (this causes loss of efficiency)\n"; 
         if( checkmovable > 1 )
            throw std::runtime_error( "because of this I stop" );
      }
      else
      {
         std::cout << "class symbol is nothrow move constructible\n";
         std::cout << "   (that is good)\n";
      }
   }

   if( debug >= 1 && 
          startsymbols. find( startsym ) == startsymbols. end( ))
   {
      std::cout << "symbol used to start not declared as start symbol: ";
      std::cout << startsym << "\n";
   }

   if( debug >= 1 && haslookahead( ))
      std::cout << "starting with lookahead = " << getlookahead( ) << "\n";

   const auto& startinfo = startsymbols. at( startsym );
   statestack. push_back( startinfo. first );
  
mainloop: 
   if( debug >= 1 ) 
      print( std::cout ); 

   if( timetosaygoodbye )
   {
      if( debug >= 2 ) 
         std::cout << "time to say goodbye!\n";

      parsing::symbol res = std::move( symbolstack. back( ));
      symbolstack. pop_back( );
      statestack. pop_back( );
      return res; 
   }
 
   size_t shift = reductioninfo. size( );  // Means undefined. 
   std::vector< size_t > redcandidates;

   const auto& redinfo = reductioninfo[ statestack. back( ) ]; 

   // If the state is non-trivial, we need a lookahead:

   if( redinfo. first != 'T' ) 
      ensurelookahead( ); 

   if( debug >= 3 && haslookahead( ))
      std::cout << "lookahead " << getlookahead( ) << "\n";

   switch( redinfo. first ) 
   {
   case 'N': 
   {
      auto p = shifts. find( 
               statesymbol( statestack.back( ), getlookahead( ). val ));
      if( p != shifts. end( ))
         shift = p -> second;
      break;
   }
   case 'D':
   {
      auto p = shifts. find(
               statesymbol( statestack.back( ), getlookahead( ). val ));
      if( p != shifts. end( ))
         shift = p -> second;
      else
         redcandidates. push_back( redinfo. second ); 
      break;
   }
   case 'H':
   {
      auto p = shifts. find(
               statesymbol( statestack. back( ), getlookahead( ). val ));
      if( p != shifts. end( ))
         shift = p -> second; 
     
      auto q = reductions. find( 
               statesymbol( statestack. back( ), getlookahead( ). val ));
      if( q != reductions. end( ))
         redcandidates = q -> second; 
      break;
   }
   case 'T':
      redcandidates. push_back( redinfo. second );
      break;   
   default:
      std::cout << redinfo.first << "\n";
      throw std::logic_error( "reduction info not recognized" );
   }
  
   if( debug >= 3 )
   { 
      if( shift != reductioninfo. size( ))
         std::cout << "shift candidate " << shift << "\n";

      if( redcandidates. size( )) 
      {
         std::cout << "reduction candidates: "; 
         for( size_t i = 0; i != redcandidates. size( ); ++ i )
            std::cout << redcandidates[i] << " ";
         std::cout << "\n";
      }
      else
         std::cout << "there are no reduction candidates\n";
   }

   // We need to find a reduction that agrees to be reduced.
   // After a reduction, we goto mainloop; 

   for( const auto& r : redcandidates ) 
   {
      if( debug >= 3 ) 
         std::cout << "trying to reduce rule " << r << "\n";

      switch(r)
      {
      case 0:
         reduce( parsing::sym_Session, std::monostate( ), 0 );
         goto mainloop;
         break;
      case 1:
         reduce( parsing::sym_Session, std::monostate( ), 3 );
         goto mainloop;
         break;
      case 2:
         reduce( parsing::sym_Session, std::monostate( ), 3 );
         goto mainloop;
         break;
      case 3:
         reduce( parsing::sym_Statement, std::monostate( ), 1 );
         goto mainloop;
         break;
      case 4:
         reduce( parsing::sym_Statement, std::monostate( ), 1 );
         goto mainloop;
         break;
      case 5:
         body5( );
         reduce( parsing::sym_def_specifier, std::monostate( ), 7 );
         goto mainloop;
         break;
      case 6:
         reduce( parsing::sym_arg_list, std::monostate( ), 0 );
         goto mainloop;
         break;
      case 7:
         reduce( parsing::sym_arg_list, std::monostate( ), 1 );
         goto mainloop;
         break;
      case 8:
         reduce( parsing::sym_term, std::monostate( ), 1 );
         goto mainloop;
         break;
      case 9:
         body9( );
         reduce( parsing::sym_struct_specifier, std::monostate( ), 4 );
         goto mainloop;
         break;
      case 10:
         reduce( parsing::sym_struct_declaration_list, std::monostate( ), 1 );
         goto mainloop;
         break;
      case 11:
         reduce( parsing::sym_struct_declaration_list, std::monostate( ), 3 );
         goto mainloop;
         break;
      case 12:
         reduce( parsing::sym_struct_declaration, std::monostate( ), 3 );
         goto mainloop;
         break;
      case 13:
         reduce( parsing::sym_type, std::monostate( ), 1 );
         goto mainloop;
         break;
      case 14:
         reduce( parsing::sym_type, std::monostate( ), 1 );
         goto mainloop;
         break;
      case 15:
         reduce( parsing::sym_func, std::monostate( ), 4 );
         goto mainloop;
         break;
      case 16:
         reduce( parsing::sym_type_list, std::monostate( ), 1 );
         goto mainloop;
         break;
      case 17:
         reduce( parsing::sym_type_list, std::monostate( ), 3 );
         goto mainloop;
         break;
 
      default:
         throw std::logic_error( "reducing unknown rule" );  
      }
   }

   if( shift < reductioninfo. size( ))
   {
      if( debug >= 2 ) 
         std::cout << "shifting S" << shift << "\n";

      if( checkattrtypes )
      {
         if( !lookahead. value( ). has_correct_attribute( ))
         {
            std::cout << "\n";
            std::cout << "tokenizer created symbol with incorrect attribute:\n";
            std::cout << "   " << lookahead. value( ) << "\n\n";

            if( checkattrtypes >= 2 )
               throw std::logic_error( "stopping because of this" ); 
         } 
      }

      statestack. push_back( shift );
      symbolstack. push_back( std::move( lookahead. value( )));
      resetlookahead( ); 

      if( timesincelasterror < 99999999 )
         ++ timesincelasterror; 

      goto mainloop;
   }

   // We accept if the stack consists of exactly the start symbol, 
   // and we have no lookahead or the lookahead is a terminator.

   if( symbolstack. size( ) == 1 &&
       symbolstack. front( ). val == startsym &&
          ( !haslookahead( ) ||
            startinfo. second. count( getlookahead( ). val )))
   {
      if( debug >= 2 ) 
         std::cout << "we accept the input\n";

      parsing::symbol res = std::move( symbolstack. front( ));
      return res;
   }

#line 1 "startpoint"

   syntaxerror( ); 
   if( timesincelasterror < maxrecovery ) 
   {
      if( debug >= 2 )
         std::cout << "trying to recover\n";

      if( debug >= 2 )
         std::cout << "time since last error = " << timesincelasterror << "\n";

      std::vector< std::pair< size_t, size_t >> shiftrecover; 
         // We collect the levels whose state can shift the  _recover_ 
         // symbol, 
         // combined with the states that will be reached after the shifts.

      for( size_t level = 0; level != statestack. size( ); ++ level )
      {
         size_t s = statestack[ level ];

         if( reductioninfo[s]. first == 'N' ||
             reductioninfo[s]. first == 'D' ||
             reductioninfo[s]. first == 'H' )
         {
            auto p = shifts. find( statesymbol( s, parsing::sym__recover_ ));
            if( p != shifts. end( ))
               shiftrecover. push_back( std::pair( level, p -> second ));
         }
      } 

      if( debug >= 1 )
      { 
         std::cout << "possible shifts after the _recover_ symbol: {";
         for( auto p = shiftrecover. begin( ); p != shiftrecover. end( ); ++ p )
         {
            if( p != shiftrecover. begin( ))
               std::cout << ", ";
            else
               std::cout << " ";
            std::cout << ( p -> first ) << "/S" << ( p -> second );
         }
         std::cout << " }\n";
      }

      if( shiftrecover. size( ) == 0 )
      {
         if( debug >= 1 )
         {
            std::cout << "no recovering shifts found\n";
            if( haslookahead( ))
               std::cout << getlookahead( ) << "\n";
            else
               std::cout << "(there is no lookahead)\n"; 
         }

         return recover_symbol( ); 
      }

      if( debug >= 2 ) 
         std::cout << "lookahead = " << getlookahead( ) << "\n";

      // As long as we have patience left, and the lookahead is not
      // in the terminator set, we try to recover: 
 
      while( timesincelasterror < maxrecovery && 
             startinfo. second. count( getlookahead( ). val ) == 0 )
      {
         // We look in shiftrecover for the highest level on
         // which we could shift current lookahead after shifting the 
         // _recover_ symbol. 

         size_t rec = shiftrecover. size( ); 
         while( rec != 0 ) 
         { 
            -- rec; 
            size_t s = shiftrecover[ rec ]. second; 
            
            if( reductioninfo[s]. first == 'N' ||
                reductioninfo[s]. first == 'D' ||
                reductioninfo[s]. first == 'H' )
            {
               auto after = shifts. find( 
                      statesymbol( s, getlookahead( ). val ));

               if( after != shifts. end( ))
               {
                  if( debug >= 2 )
                  {
                     std::cout << rec << " is candidate\n";
                     std::cout << "recovery will be into state ";
                     std::cout << after -> second << "\n";
                  }

                  while( statestack. size() > shiftrecover[ rec ]. first + 1 )
                  {
                     statestack. pop_back( );
                     symbolstack. pop_back( );  
                  } 
                  
                  statestack. push_back(s);
                  symbolstack. push_back( recover_symbol( ));

                  statestack. push_back( after -> second );
                  symbolstack. push_back( std::move( lookahead. value( ) ));

                  lookahead. reset( );

                  if( debug >= 2 ) 
                  {
                     std::cout <<  "recovery complete" << "\n";
                  }
                  timesincelasterror = 0;
                  goto mainloop; 
               } 
            }
         }

         // We throw away the current lookahead,
         // and increase the time since the last error. 
 
         if( debug >= 1 ) 
         {
            std::cout << "not yet recovered, time since last error = ";
            std::cout << timesincelasterror << "\n";
         }
         lookahead. reset( ); 
         ensurelookahead( );  

         if( timesincelasterror < 99999999 )
            ++ timesincelasterror; 
      }
   }

   // That's it. Game over. We lost.

   if( debug )
   {
      if( timesincelasterror < maxrecovery ) 
         std::cout << "reached a terminator\n";
      else
         std::cout << "recovery ran out of patience\n";
   }

#if true
   return parsing::symbol( parsing::sym__recover_,
                  std::optional< parsing::symbol::infotype > ( ) );
#else
   return parsing::symbol( parsing::sym__recover_ );
#endif

}


parsing::symbol parsing::parser::recover_symbol( ) 
{
#if true
   return parsing::symbol( parsing::sym__recover_,
                  std::optional< parsing::symbol::infotype > ( ));
#else
   return parsing::symbol( parsing::sym__recover_ );
#endif
}


size_t 
parsing::parser::match( const expectation& exp ) const
{
   size_t stackpos = symbolstack. size( );
   size_t triggerpos = exp. trigger. size( );
      // Both use predecrement consistently.

   while( triggerpos )
   {
      -- triggerpos;

      size_t skipped = 0;

   loop:
      // It is possible to write this with a while loop, but
      // the result looks terrible.

      if( stackpos == 0 || skipped > exp. trigger[ triggerpos ]. maxskip )
         return symbolstack. size( ) + 1;

      -- stackpos;
      if( !exp. trigger[ triggerpos ]. set. contains( 
                    symbolstack[ stackpos ]. val ))
      {
         ++ skipped;
         goto loop;
      }
   }

   return stackpos;
}


#if ! false 

void
parsing::parser::syntaxerror( )
{
   if( timesincelasterror + 1 <= maxtrialperiod )
   {
      timesincelasterror = 0;
      return;
   }

   size_t bestpos = symbolstack. size( ) + 1;
   auto besterror = errormessages. end( );

   for( auto p = errormessages. begin( ); p != errormessages. end( ); ++ p )
   {
      size_t pos = match(*p);
      if( pos < bestpos )
      {
         bestpos = pos;
         besterror = p;
      }
   }

   if( bestpos <= symbolstack. size( ))
   {
      std::cout << "expected " << ( besterror -> expected );
      if( haslookahead( ))
      {
         std::cout << " instead of " << getlookahead( ). val;
      }
   }
   else
   {
      if( haslookahead( ))
         std::cout << "unexpected " << getlookahead( ). val;
      else
         std::cout << "syntax error";
   }

#if true
   // If symbols have location information, we try to extract a location.
   // We first check lookahead, then backwards on the parse stack, for
   // the first symbol that has location information.

   std::optional< parsing::symbol::infotype > info;
   if( haslookahead( ))
      info = getlookahead( ). info;

   auto p = symbolstack. end( );
   while( p != symbolstack. begin( ) && !info. has_value( ))
   {
      -- p;
      if( p -> info. has_value( ))
         info = p -> info;
   }

   if( info. has_value( ))
      std::cout << " at position " << info. value( );
#endif

   std::cout << "\n";
   timesincelasterror = 0; 
}

#endif


void
parsing::parser::reset( )
{
   if( debug >= 1 )
      std::cout << "Resetting parser\n";

   statestack. clear( );
   symbolstack. clear( );

   if( debug >= 1 && haslookahead( ))
      std::cout << "lookahead still contains " << getlookahead( ) << "\n";

   timetosaygoodbye = false;
}


void 
parsing::parser::print( std::ostream& out ) const
{
   out << "Statestack: ";
   for( auto s : statestack )
      out << "S" << s << " ";
   out << "\n";

   out << "Symbolstack: ";
   for( const auto& s : symbolstack )
      out << s << "   ";
   out << "\n";
   if( timesincelasterror < 1000 )
      out << "last error was " << timesincelasterror << " symbols ago\n";

}

const std::unordered_map< parsing::symbolval, std::pair< size_t, std::unordered_set< parsing::symbolval >>> parsing::parser::startsymbols =
{
   { parsing::sym_Session, { 0, { parsing::sym_EOF }} }
};

const std::vector< std::pair< char, size_t >> parsing::parser::reductioninfo =
{
   { 'D', 0 }, { 'N', 0 }, { 'N', 0 }, { 'T', 3 }, { 'T', 4 }, { 'N', 0 }, { 'N', 0 }, { 'N', 0 },
   { 'N', 0 }, { 'T', 2 }, { 'N', 0 }, { 'T', 1 }, { 'N', 0 }, { 'D', 6 }, { 'N', 0 }, { 'D', 10 },
   { 'T', 9 }, { 'T', 7 }, { 'N', 0 }, { 'N', 0 }, { 'N', 0 }, { 'N', 0 }, { 'T', 13 }, { 'T', 14 },
   { 'D', 12 }, { 'T', 11 }, { 'N', 0 }, { 'N', 0 }, { 'T', 8 }, { 'T', 5 }, { 'D', 16 }, { 'N', 0 },
   { 'T', 15 }, { 'N', 0 }, { 'D', 17 }
};

const parsing::parser::statesymbol::map< size_t > parsing::parser::shifts =
{
   { { 33, parsing::sym_IDENTIFIER }, 22 }, { { 33, parsing::sym_func }, 23 }, { { 31, parsing::sym_COMMA }, 33 }, { { 30, parsing::sym_LPAR }, 27 }, { { 34, parsing::sym_LPAR }, 27 },
   { { 27, parsing::sym_IDENTIFIER }, 22 }, { { 27, parsing::sym_type }, 30 }, { { 26, parsing::sym_IDENTIFIER }, 28 }, { { 26, parsing::sym_term }, 29 }, { { 24, parsing::sym_LPAR }, 27 },
   { { 21, parsing::sym_ASSIGN }, 26 }, { { 10, parsing::sym_LPAR }, 13 }, { { 19, parsing::sym_func }, 23 }, { { 5, parsing::sym_SEMICOLON }, 9 }, { { 1, parsing::sym__recover_ }, 5 },
   { { 1, parsing::sym_STRUCT }, 2 }, { { 1, parsing::sym_Statement }, 7 }, { { 1, parsing::sym_DEF }, 6 }, { { 27, parsing::sym_type_list }, 31 }, { { 2, parsing::sym_IDENTIFIER }, 8 },
   { { 7, parsing::sym_SEMICOLON }, 11 }, { { 1, parsing::sym_struct_specifier }, 3 }, { { 19, parsing::sym_IDENTIFIER }, 22 }, { { 15, parsing::sym_COMMA }, 20 }, { { 33, parsing::sym_type }, 34 },
   { { 12, parsing::sym_struct_declaration_list }, 16 }, { { 1, parsing::sym_def_specifier }, 4 }, { { 12, parsing::sym_struct_declaration }, 15 }, { { 13, parsing::sym_IDENTIFIER }, 14 }, { { 6, parsing::sym_IDENTIFIER }, 10 },
   { { 13, parsing::sym_struct_declaration_list }, 17 }, { { 12, parsing::sym_IDENTIFIER }, 14 }, { { 13, parsing::sym_arg_list }, 18 }, { { 13, parsing::sym_struct_declaration }, 15 }, { { 20, parsing::sym_struct_declaration }, 15 },
   { { 14, parsing::sym_COLON }, 19 }, { { 27, parsing::sym_func }, 23 }, { { 18, parsing::sym_RPAR }, 21 }, { { 19, parsing::sym_type }, 24 }, { { 31, parsing::sym_RPAR }, 32 },
   { { 0, parsing::sym_Session }, 1 }, { { 20, parsing::sym_struct_declaration_list }, 25 }, { { 8, parsing::sym_ASSIGN }, 12 }, { { 20, parsing::sym_IDENTIFIER }, 14 }
};

const parsing::parser::statesymbol::map< std::vector< size_t >> parsing::parser::reductions =
{
   
};


const std::vector< parsing::parser::expectation > parsing::parser::errormessages =
{

};


