
// The code below was generated by Maphoon 2024.

// Definition of struct symbol:

#ifndef PARSING_SYMBOL_
#define PARSING_SYMBOL_    1

#include <iostream>
#include <variant>
#include <optional>
#include <concepts>
#include <stdexcept>

#line 26 "parsing/grammar.m"
 #include "location.h" 

namespace parsing { 

   enum symbolval
   {
      sym__recover_, sym_FRM, sym_DEF, sym_STRUCT, 
      sym_IDENTIFIER, sym_OR, sym_EXISTS, sym_FORALL, 
      sym_COLON, sym_ASSIGN, sym_COMMA, sym_func, 
      sym_SCANERROR, sym_struct_specifier, sym_type, sym_EQ, 
      sym_AND, sym_DOT, sym_GT_EQ, sym_struct_declaration, 
      sym_RBRACKET, sym_def_specifier, sym_LPAR, sym_struct_declaration_list, 
      sym_EOF, sym_IMPLY, sym_term, sym_Statement, 
      sym_arg_list, sym_COMMENT, sym_Session, sym_identifier_list, 
      sym_FILEBAD, sym_SEMICOLON, sym_GT, sym_EMPTY, 
      sym_Expr, sym_RPAR, sym_WHITESPACE, sym_LBRACE, 
      sym_RBRACE, sym_LBRACKET, sym_type_list, sym_LT, 
      sym_LT_EQ
   };

   const char* getcstring( symbolval );

   inline std::ostream& operator << ( std::ostream& out, symbolval val )
      { out << getcstring( val );  return out; }

   struct symbol
   {
      using attrtype = std::variant < std::monostate, std::string > ;

      using infotype = location;

      symbolval val;
      std::optional<infotype> info;
      attrtype attr;

      symbol( ) = delete;
      symbol( const symbol& ) = default;
      symbol( symbol&& ) noexcept = default;
      symbol& operator = ( const symbol& ) = default;
      symbol& operator = ( symbol&& ) noexcept = default;
      ~symbol( ) = default;

      // Construct symbol with void attribute:

      symbol( symbolval val,
              const std::optional<infotype> & info )
       : val( val ),
         info( info )
      { }

      // Template constructor from const attribute& :

      template< typename _T >
         requires std::convertible_to< _T, attrtype > && std::copy_constructible< _T >
      symbol( symbolval val,
              const std::optional<infotype> & info,
              const _T & attr )
       : val( val ),
         info( info ),
         attr( attr )
      { }

      // Template onstructor from attribute&& :

      template< typename _T >
         requires std::convertible_to< _T, attrtype > && std::move_constructible< _T >
      symbol( symbolval val,
              const std::optional<infotype> & info,
              _T && attr )
       : val( val ),
         info( info ),
         attr( std::move( attr ))
      { }

      void print( std::ostream& out ) const;

      bool has_correct_attribute( ) const;

      template< typename T > T& get( )
         { return std::get<T> ( attr ); }
      
      template< typename T > const T& get( ) const
         { return std::get<T> ( attr ); }
      
   };

   inline
   std::ostream& operator << ( std::ostream& out, const symbol& sym )
      { sym. print( out ); return out; }


}

#endif


