
// Parser generated by Maphoon 2022.
// Written by Hans de Nivelle, March 2021-May 2022.
// See the licence that was included with the code.

#include "parser.h"

#line 59 "grammar.m"


   double fact( unsigned int _n )
   {
      double res = 1.0;
      while( _n )
      {
         res *= _n;
         -- _n;
      }
      return res;
   }

   void printerrors( const std::vector< std::string > & errors, 
                     std::ostream& out )
   {
      std::cout << "Errors:\n";
      for( const auto& err : errors )
         out << "   " << err << "\n";
   }



#line 207 "idee.x"


size_t 
parser::statesymbol::hash::operator( ) ( const statesymbol& ss ) const
{
   // After some trying, and looking at the distribution in the map,
   // this gives decent results:

   auto s = ss. state;
   auto t = ss. val;
   size_t h = s + 41 * t + t * t; 
   h ^= ( h >> 7 );
   return h;
}

bool
parser::statesymbol::equal_to::operator( ) ( const statesymbol& ss1,
                                                            const statesymbol& ss2 ) const
{
   return ss1. state == ss2. state && ss1. val == ss2. val;
}


// Definitions of the reduction functions:

auto parser::body2( ) -> void
{
#line 94 "grammar.m"

   if( errorlog. empty( ))
      std::cout << "   --> " << (topsymbol(2).get<double>()) << "\n";
   else
   {
      printerrors( errorlog, std::cout ); 
      errorlog. clear( ); 
   }
}

auto parser::body3( ) -> void
{
#line 106 "grammar.m"

   if( errorlog. empty( )) 
   {
      std::cout << "   --> assigning " << (topsymbol(4).get<std::string>()) << " := " << (topsymbol(2).get<double>()) << "\n";
      memory[(topsymbol(4).get<std::string>())] = (topsymbol(2).get<double>()); 
   }
   else
   {
      printerrors( errorlog, std::cout ); 
      errorlog. clear( ); 
   }
}

auto parser::body4( ) -> void
{
#line 120 "grammar.m"

   std::cout << "\n";
   std::cout << "quitting\n"; timetosaygoodbye = true;
}

auto parser::body5( ) -> void
{
#line 125 "grammar.m"

   std::cout << "Memory:\n";
   for( const auto& p : memory )
      std::cout << "   " << p. first << " : " << p. second << "\n";
   std::cout << "\n\n";
}

auto parser::body6( ) -> void
{
#line 131 "grammar.m"
 debug = 1; }

auto parser::body7( ) -> void
{
#line 132 "grammar.m"
 debug = 0; }

auto parser::body8( ) -> void
{
#line 134 "grammar.m"

   if( debug ) 
      std::cout << "recovered from syntax error\n\n";
}

auto parser::body9( ) -> double
{
#line 140 "grammar.m"
 return (topsymbol(3).get<double>()) + (topsymbol(1).get<double>()); }

auto parser::body10( ) -> double
{
#line 141 "grammar.m"
 return (topsymbol(3).get<double>()) - (topsymbol(1).get<double>()); }

auto parser::body11( ) -> double
{
#line 142 "grammar.m"
 return (topsymbol(1).get<double>()); }

auto parser::body12( ) -> double
{
#line 145 "grammar.m"
 return (topsymbol(3).get<double>()) * (topsymbol(1).get<double>()); }

auto parser::body13( ) -> double
{
#line 148 "grammar.m"

   if( (topsymbol(1).get<double>()) == 0.0 ) 
   {
      errorlog. push_back( "division by zero" ); 
      (topsymbol(1).get<double>()) = 1.0;   // invent a value. 
   }
   return (topsymbol(3).get<double>()) / (topsymbol(1).get<double>());  
}

auto parser::body14( ) -> double
{
#line 159 "grammar.m"

   if( (topsymbol(1).get<double>()) == 0.0 )
   {
      errorlog. push_back( "modulo by zero" );
      (topsymbol(1).get<double>()) = 1.0;
   }
    
   return (topsymbol(3).get<double>()) - (topsymbol(1).get<double>()) * floor( (topsymbol(3).get<double>()) / (topsymbol(1).get<double>()) ); 
}

auto parser::body15( ) -> double
{
#line 169 "grammar.m"
 return (topsymbol(1).get<double>()); }

auto parser::body16( ) -> double
{
#line 172 "grammar.m"
 return -(topsymbol(1).get<double>()); }

auto parser::body17( ) -> double
{
#line 173 "grammar.m"
 return (topsymbol(1).get<double>()); }

auto parser::body18( ) -> double
{
#line 174 "grammar.m"
 return (topsymbol(1).get<double>()); }

auto parser::body19( ) -> double
{
#line 178 "grammar.m"

   unsigned int f = static_cast< unsigned int >
         ( floor( (topsymbol(2).get<double>()) + 0.0001 ));
   return fact(f);  
}

auto parser::body20( ) -> double
{
#line 184 "grammar.m"
 return (topsymbol(2).get<double>()); }

auto parser::body21( ) -> double
{
#line 186 "grammar.m"

      if( memory. contains((topsymbol(1).get<std::string>())))
         return memory. at( (topsymbol(1).get<std::string>()) );
      else
      {
         errorlog. push_back( std::string( "variable " ) + (topsymbol(1).get<std::string>()) + 
                              " is undefined " );
         return 0.0;  
      }
   }

auto parser::body22( ) -> double
{
#line 197 "grammar.m"
 return (topsymbol(1).get<double>()); }

auto parser::body23( ) -> double
{
#line 200 "grammar.m"
 
      if( (topsymbol(4).get<std::string>()) == "sin" && (topsymbol(2).get<std::vector<double>>()). size( ) == 1 ) 
         return sin( (topsymbol(2).get<std::vector<double>>())[0] ); 

      if( (topsymbol(4).get<std::string>()) == "cos" && (topsymbol(2).get<std::vector<double>>()). size( ) == 1 )
         return cos( (topsymbol(2).get<std::vector<double>>())[0] );

      if( (topsymbol(4).get<std::string>()) == "sqrt" && (topsymbol(2).get<std::vector<double>>()). size( ) == 1 )
         return sqrt( (topsymbol(2).get<std::vector<double>>())[0] ); 

      if( (topsymbol(4).get<std::string>()) == "pow" && (topsymbol(2).get<std::vector<double>>()). size( ) == 2 )
      {
         return pow( (topsymbol(2).get<std::vector<double>>())[0], (topsymbol(2).get<std::vector<double>>())[1] );
      }
  
      if( (topsymbol(4).get<std::string>()) == "exp" && (topsymbol(2).get<std::vector<double>>()). size( ) == 1 )
      {
         return exp( (topsymbol(2).get<std::vector<double>>())[0] );
      }

      if( (topsymbol(4).get<std::string>()) == "log" && (topsymbol(2).get<std::vector<double>>()). size( ) == 1 )
      {
         return log( (topsymbol(2).get<std::vector<double>>())[0] );
      }

      if( (topsymbol(4).get<std::string>()) == "sinh" && (topsymbol(2).get<std::vector<double>>()). size( ) == 1 )
      {
         return sinh( (topsymbol(2).get<std::vector<double>>())[0] );
      }

 
      errorlog. push_back( std::string( "calling unknown function " ) + (topsymbol(4).get<std::string>()) );
      return 0.0;
   }

auto parser::body24( ) -> std::vector<double>
{
#line 237 "grammar.m"
  return { (topsymbol(1).get<double>()) };   }

auto parser::body25( ) -> std::vector<double>
{
#line 238 "grammar.m"
 (topsymbol(3).get<std::vector<double>>()). push_back((topsymbol(1).get<double>())); return (topsymbol(3).get<std::vector<double>>()); }

short parser::cond26( ) const
{
#line 242 "grammar.m"
 return (topsymbol(1).get<std::string>()) == "quit"; }

short parser::cond27( ) const
{
#line 246 "grammar.m"
 return (topsymbol(1).get<std::string>()) == "show"; }

short parser::cond28( ) const
{
#line 250 "grammar.m"
 return (topsymbol(1).get<std::string>()) == "debug"; }

short parser::cond29( ) const
{
#line 254 "grammar.m"
 return (topsymbol(1).get<std::string>()) == "nodebug"; }



#line 1 "reduce"

void parser::reduce( symbolval leftval,
               symbol::attrtype&& attr, size_t rightsize )
{
   if( debug >= 2 )
   {
      std::cout << "popping " << rightsize << " state(s) and symbol(s) "; 
      std::cout << "from the stack and reducing into " << leftval << "\n";
   }

#if false
   // This works only if symbol has an infotype: 

   std::optional< symbol::infotype > info;
      // For the first stack entry that has an info, we move it into here. 
      // For later stack entries that have an info, we merge them
      // with the first info. The idea is that info has set semantics. 

   for( auto p = symbolstack. end( ) - rightsize; 
        p != symbolstack. end( ); ++ p ) 
   {
      // If we encounter first defined, we move into info. 
      // 

      if( p -> info. has_value( )) 
      {
         if( info. has_value( ))
            info.value( ). merge( std::move( p -> info.value() ));
         else
            info = std::move( p -> info );
      }
   }
#endif 

   while( rightsize )
   {
      statestack. pop_back( );
      symbolstack. pop_back( );
      -- rightsize; 
   }
  
   // It remains to do the goto: 

   statestack. push_back( shifts. at( { statestack. back( ), leftval } ));

#if false
   symbolstack. emplace_back( leftval, info, std::move( attr ));
#else
   symbolstack. emplace_back( leftval, std::move( attr ));
#endif 
}

#line 1 "parse"

symbol 
parser::parse( symbolval startsym )
{
   if( debug )
      std::cout << "Starting parser:\n";

   if( checkmovable ) 
   {
      if( ! std::is_nothrow_move_constructible<symbol> :: value )
      {
         std::cout << "class symbol is not nothrow move constructible\n";
         std::cout << "   (this causes loss of efficiency)\n"; 
         if( checkmovable > 1 )
            throw std::runtime_error( "because of this I stop" );
      }
      else
      {
         std::cout << "class symbol is nothrow move constructible\n";
         std::cout << "   (that is good)\n";
      }
   }

   if( debug >= 1 && 
          startsymbols. find( startsym ) == startsymbols. end( ))
   {
      std::cout << "symbol used to start not declared as start symbol: ";
      std::cout << startsym << "\n";
   }

   if( debug >= 1 && haslookahead( ))
      std::cout << "starting with lookahead = " << getlookahead( ) << "\n";

   const auto& startinfo = startsymbols. at( startsym );
   statestack. push_back( startinfo. first );
  
mainloop: 
   if( debug >= 1 ) 
      print( std::cout ); 

   if( timetosaygoodbye )
   {
      if( debug >= 2 ) 
         std::cout << "time to say goodbye!\n";

      symbol res = std::move( symbolstack. back( ));
      symbolstack. pop_back( );
      statestack. pop_back( );
      return res; 
   }
 
   size_t shift = reductioninfo. size( );  // Means undefined. 
   std::vector< size_t > redcandidates;

   const auto& redinfo = reductioninfo[ statestack. back( ) ]; 

   // If the state is non-trivial, we need a lookahead:

   if( redinfo. first != 'T' ) 
      ensurelookahead( ); 

   if( debug >= 3 && haslookahead( ))
      std::cout << "lookahead " << getlookahead( ) << "\n";

   switch( redinfo. first ) 
   {
   case 'N': 
   {
      auto p = shifts. find( 
               statesymbol( statestack.back( ), getlookahead( ). val ));
      if( p != shifts. end( ))
         shift = p -> second;
      break;
   }
   case 'D':
   {
      auto p = shifts. find(
               statesymbol( statestack.back( ), getlookahead( ). val ));
      if( p != shifts. end( ))
         shift = p -> second;
      else
         redcandidates. push_back( redinfo. second ); 
      break;
   }
   case 'H':
   {
      auto p = shifts. find(
               statesymbol( statestack. back( ), getlookahead( ). val ));
      if( p != shifts. end( ))
         shift = p -> second; 
     
      auto q = reductions. find( 
               statesymbol( statestack. back( ), getlookahead( ). val ));
      if( q != reductions. end( ))
         redcandidates = q -> second; 
      break;
   }
   case 'T':
      redcandidates. push_back( redinfo. second );
      break;   
   default:
      std::cout << redinfo.first << "\n";
      throw std::logic_error( "reduction info not recognized" );
   }
  
   if( debug >= 3 )
   { 
      if( shift != reductioninfo. size( ))
         std::cout << "shift candidate " << shift << "\n";

      if( redcandidates. size( )) 
      {
         std::cout << "reduction candidates: "; 
         for( size_t i = 0; i != redcandidates. size( ); ++ i )
            std::cout << redcandidates[i] << " ";
         std::cout << "\n";
      }
      else
         std::cout << "there are no reduction candidates\n";
   }

   // We need to find a reduction that agrees to be reduced.
   // After a reduction, we goto mainloop; 

   for( const auto& r : redcandidates ) 
   {
      if( debug >= 3 ) 
         std::cout << "trying to reduce rule " << r << "\n";

      switch(r)
      {
      case 0:
         reduce( sym_Session, std::monostate( ), 2 );
         goto mainloop;
         break;
      case 1:
         reduce( sym_Session, std::monostate( ), 0 );
         goto mainloop;
         break;
      case 2:
         body2( );
         reduce( sym_Command, std::monostate( ), 2 );
         goto mainloop;
         break;
      case 3:
         body3( );
         reduce( sym_Command, std::monostate( ), 4 );
         goto mainloop;
         break;
      case 4:
         body4( );
         reduce( sym_Command, std::monostate( ), 2 );
         goto mainloop;
         break;
      case 5:
         body5( );
         reduce( sym_Command, std::monostate( ), 2 );
         goto mainloop;
         break;
      case 6:
         body6( );
         reduce( sym_Command, std::monostate( ), 2 );
         goto mainloop;
         break;
      case 7:
         body7( );
         reduce( sym_Command, std::monostate( ), 2 );
         goto mainloop;
         break;
      case 8:
         body8( );
         reduce( sym_Command, std::monostate( ), 2 );
         goto mainloop;
         break;
      case 9:
         reduce( sym_E, body9( ), 3 );
         goto mainloop;
         break;
      case 10:
         reduce( sym_E, body10( ), 3 );
         goto mainloop;
         break;
      case 11:
         reduce( sym_E, body11( ), 1 );
         goto mainloop;
         break;
      case 12:
         reduce( sym_F, body12( ), 3 );
         goto mainloop;
         break;
      case 13:
         reduce( sym_F, body13( ), 3 );
         goto mainloop;
         break;
      case 14:
         reduce( sym_F, body14( ), 3 );
         goto mainloop;
         break;
      case 15:
         reduce( sym_F, body15( ), 1 );
         goto mainloop;
         break;
      case 16:
         reduce( sym_G, body16( ), 2 );
         goto mainloop;
         break;
      case 17:
         reduce( sym_G, body17( ), 2 );
         goto mainloop;
         break;
      case 18:
         reduce( sym_G, body18( ), 1 );
         goto mainloop;
         break;
      case 19:
         reduce( sym_H, body19( ), 2 );
         goto mainloop;
         break;
      case 20:
         reduce( sym_H, body20( ), 3 );
         goto mainloop;
         break;
      case 21:
         reduce( sym_H, body21( ), 1 );
         goto mainloop;
         break;
      case 22:
         reduce( sym_H, body22( ), 1 );
         goto mainloop;
         break;
      case 23:
         reduce( sym_H, body23( ), 4 );
         goto mainloop;
         break;
      case 24:
         reduce( sym_Arguments, body24( ), 1 );
         goto mainloop;
         break;
      case 25:
         reduce( sym_Arguments, body25( ), 3 );
         goto mainloop;
         break;
      case 26:
         if( short s = cond26(); s > 0 )
         {
            reduce( sym_Quit, std::monostate( ), 1 );
            goto mainloop;
         }
         else
            if( s < 0 ) shift = reductioninfo. size( );
         break;
      case 27:
         if( short s = cond27(); s > 0 )
         {
            reduce( sym_Show, std::monostate( ), 1 );
            goto mainloop;
         }
         else
            if( s < 0 ) shift = reductioninfo. size( );
         break;
      case 28:
         if( short s = cond28(); s > 0 )
         {
            reduce( sym_Debug, std::monostate( ), 1 );
            goto mainloop;
         }
         else
            if( s < 0 ) shift = reductioninfo. size( );
         break;
      case 29:
         if( short s = cond29(); s > 0 )
         {
            reduce( sym_Nodebug, std::monostate( ), 1 );
            goto mainloop;
         }
         else
            if( s < 0 ) shift = reductioninfo. size( );
         break;
 
      default:
         throw std::logic_error( "reducing unknown rule" );  
      }
   }

   if( shift < reductioninfo. size( ))
   {
      if( debug >= 2 ) 
         std::cout << "shifting S" << shift << "\n";

      if( checkattrtypes )
      {
         if( !lookahead. value( ). has_correct_attribute( ))
         {
            std::cout << "\n";
            std::cout << "tokenizer created symbol with incorrect attribute:\n";
            std::cout << "   " << lookahead. value( ) << "\n\n";

            if( checkattrtypes >= 2 )
               throw std::logic_error( "stopping because of this" ); 
         } 
      }

      statestack. push_back( shift );
      symbolstack. push_back( std::move( lookahead. value( )));
      resetlookahead( ); 

      if( timesincelasterror < 99999999 )
         ++ timesincelasterror; 

      goto mainloop;
   }

   // We accept if the stack consists of exactly the start symbol, 
   // and we have no lookahead or the lookahead is a terminator.

   if( symbolstack. size( ) == 1 &&
       symbolstack. front( ). val == startsym &&
          ( !haslookahead( ) ||
            startinfo. second. count( getlookahead( ). val )))
   {
      if( debug >= 2 ) 
         std::cout << "we accept the input\n";

      symbol res = std::move( symbolstack. front( ));
      return res;
   }

#line 1 "startpoint"

   syntaxerror( ); 
   if( timesincelasterror < maxrecovery ) 
   {
      if( debug >= 2 )
         std::cout << "trying to recover\n";

      if( debug >= 2 )
         std::cout << "time since last error = " << timesincelasterror << "\n";

      std::vector< std::pair< size_t, size_t >> shiftrecover; 
         // We collect the levels whose state can shift the  _recover_ 
         // symbol, 
         // combined with the states that will be reached after the shifts.

      for( size_t level = 0; level != statestack. size( ); ++ level )
      {
         size_t s = statestack[ level ];

         if( reductioninfo[s]. first == 'N' ||
             reductioninfo[s]. first == 'D' ||
             reductioninfo[s]. first == 'H' )
         {
            auto p = shifts. find( statesymbol( s, sym__recover_ ));
            if( p != shifts. end( ))
               shiftrecover. push_back( std::pair( level, p -> second ));
         }
      } 

      if( debug >= 1 )
      { 
         std::cout << "possible shifts after the _recover_ symbol: {";
         for( auto p = shiftrecover. begin( ); p != shiftrecover. end( ); ++ p )
         {
            if( p != shiftrecover. begin( ))
               std::cout << ", ";
            else
               std::cout << " ";
            std::cout << ( p -> first ) << "/S" << ( p -> second );
         }
         std::cout << " }\n";
      }

      if( shiftrecover. size( ) == 0 )
      {
         if( debug >= 1 )
         {
            std::cout << "no recovering shifts found\n";
            if( haslookahead( ))
               std::cout << getlookahead( ) << "\n";
            else
               std::cout << "(there is no lookahead)\n"; 
         }

         return recover_symbol( ); 
      }

      if( debug >= 2 ) 
         std::cout << "lookahead = " << getlookahead( ) << "\n";

      // As long as we have patience left, and the lookahead is not
      // in the terminator set, we try to recover: 
 
      while( timesincelasterror < maxrecovery && 
             startinfo. second. count( getlookahead( ). val ) == 0 )
      {
         // We look in shiftrecover for the highest level on
         // which we could shift current lookahead after shifting the 
         // _recover_ symbol. 

         size_t rec = shiftrecover. size( ); 
         while( rec != 0 ) 
         { 
            -- rec; 
            size_t s = shiftrecover[ rec ]. second; 
            
            if( reductioninfo[s]. first == 'N' ||
                reductioninfo[s]. first == 'D' ||
                reductioninfo[s]. first == 'H' )
            {
               auto after = shifts. find( 
                      statesymbol( s, getlookahead( ). val ));

               if( after != shifts. end( ))
               {
                  if( debug >= 2 )
                  {
                     std::cout << rec << " is candidate\n";
                     std::cout << "recovery will be into state ";
                     std::cout << after -> second << "\n";
                  }

                  while( statestack. size() > shiftrecover[ rec ]. first + 1 )
                  {
                     statestack. pop_back( );
                     symbolstack. pop_back( );  
                  } 
                  
                  statestack. push_back(s);
                  symbolstack. push_back( recover_symbol( ));

                  statestack. push_back( after -> second );
                  symbolstack. push_back( std::move( lookahead. value( ) ));

                  lookahead. reset( );

                  if( debug >= 2 ) 
                  {
                     std::cout <<  "recovery complete" << "\n";
                  }
                  timesincelasterror = 0;
                  goto mainloop; 
               } 
            }
         }

         // We throw away the current lookahead,
         // and increase the time since the last error. 
 
         if( debug >= 1 ) 
         {
            std::cout << "not yet recovered, time since last error = ";
            std::cout << timesincelasterror << "\n";
         }
         lookahead. reset( ); 
         ensurelookahead( );  

         if( timesincelasterror < 99999999 )
            ++ timesincelasterror; 
      }
   }

   // That's it. Game over. We lost.

   if( debug )
   {
      if( timesincelasterror < maxrecovery ) 
         std::cout << "reached a terminator\n";
      else
         std::cout << "recovery ran out of patience\n";
   }

#if false
   return symbol( sym__recover_,
                  std::optional< symbol::infotype > ( ) );
#else
   return symbol( sym__recover_ );
#endif

}


symbol parser::recover_symbol( ) 
{
#if false
   return symbol( sym__recover_,
                  std::optional< symbol::infotype > ( ));
#else
   return symbol( sym__recover_ );
#endif
}


size_t 
parser::match( const expectation& exp ) const
{
   size_t stackpos = symbolstack. size( );
   size_t triggerpos = exp. trigger. size( );
      // Both use predecrement consistently.

   while( triggerpos )
   {
      -- triggerpos;

      size_t skipped = 0;

   loop:
      // It is possible to write this with a while loop, but
      // the result looks terrible.

      if( stackpos == 0 || skipped > exp. trigger[ triggerpos ]. maxskip )
         return symbolstack. size( ) + 1;

      -- stackpos;
      if( !exp. trigger[ triggerpos ]. set. contains( 
                    symbolstack[ stackpos ]. val ))
      {
         ++ skipped;
         goto loop;
      }
   }

   return stackpos;
}


#if ! false 

void
parser::syntaxerror( )
{
   if( timesincelasterror + 1 <= maxtrialperiod )
   {
      timesincelasterror = 0;
      return;
   }

   size_t bestpos = symbolstack. size( ) + 1;
   auto besterror = errormessages. end( );

   for( auto p = errormessages. begin( ); p != errormessages. end( ); ++ p )
   {
      size_t pos = match(*p);
      if( pos < bestpos )
      {
         bestpos = pos;
         besterror = p;
      }
   }

   if( bestpos <= symbolstack. size( ))
   {
      std::cout << "expected " << ( besterror -> expected );
      if( haslookahead( ))
      {
         std::cout << " instead of " << getlookahead( ). val;
      }
   }
   else
   {
      if( haslookahead( ))
         std::cout << "unexpected " << getlookahead( ). val;
      else
         std::cout << "syntax error";
   }

#if false
   // If symbols have location information, we try to extract a location.
   // We first check lookahead, then backwards on the parse stack, for
   // the first symbol that has location information.

   std::optional< symbol::infotype > info;
   if( haslookahead( ))
      info = getlookahead( ). info;

   auto p = symbolstack. end( );
   while( p != symbolstack. begin( ) && !info. has_value( ))
   {
      -- p;
      if( p -> info. has_value( ))
         info = p -> info;
   }

   if( info. has_value( ))
      std::cout << " at position " << info. value( );
#endif

   std::cout << "\n";
   timesincelasterror = 0; 
}

#endif


void
parser::reset( )
{
   if( debug >= 1 )
      std::cout << "Resetting parser\n";

   statestack. clear( );
   symbolstack. clear( );

   if( debug >= 1 && haslookahead( ))
      std::cout << "lookahead still contains " << getlookahead( ) << "\n";

   timetosaygoodbye = false;
}


void 
parser::print( std::ostream& out ) const
{
   out << "Statestack: ";
   for( auto s : statestack )
      out << "S" << s << " ";
   out << "\n";

   out << "Symbolstack: ";
   for( const auto& s : symbolstack )
      out << s << "   ";
   out << "\n";
   if( timesincelasterror < 1000 )
      out << "last error was " << timesincelasterror << " symbols ago\n";

}

const std::unordered_map< symbolval, std::pair< size_t, std::unordered_set< symbolval >>> parser::startsymbols =
{
   { sym_Session, { 0, { sym_EOF }} }
};

const std::vector< std::pair< char, size_t >> parser::reductioninfo =
{
   { 'D', 1 }, { 'N', 0 }, { 'T', 22 }, { 'N', 0 }, { 'D', 11 }, { 'H', 0 }, { 'N', 0 }, { 'N', 0 },
   { 'N', 0 }, { 'N', 0 }, { 'N', 0 }, { 'N', 0 }, { 'N', 0 }, { 'T', 0 }, { 'T', 15 }, { 'N', 0 },
   { 'D', 18 }, { 'N', 0 }, { 'D', 21 }, { 'N', 0 }, { 'N', 0 }, { 'N', 0 }, { 'N', 0 }, { 'N', 0 },
   { 'T', 17 }, { 'T', 16 }, { 'T', 5 }, { 'T', 6 }, { 'T', 7 }, { 'N', 0 }, { 'N', 0 }, { 'T', 2 },
   { 'T', 8 }, { 'T', 4 }, { 'T', 19 }, { 'T', 20 }, { 'T', 14 }, { 'T', 13 }, { 'T', 12 }, { 'N', 0 },
   { 'D', 24 }, { 'N', 0 }, { 'D', 9 }, { 'D', 10 }, { 'N', 0 }, { 'T', 23 }, { 'T', 3 }, { 'D', 25 }
};

const parser::statesymbol::map< size_t > parser::shifts =
{
   { { 44, sym_G }, 14 }, { { 44, sym_DOUBLE }, 2 }, { { 44, sym_H }, 16 }, { { 44, sym_IDENT }, 18 }, { { 20, sym_G }, 37 },
   { { 3, sym_MINUS }, 7 }, { { 22, sym_Arguments }, 39 }, { { 44, sym_MINUS }, 7 }, { { 44, sym_F }, 4 }, { { 15, sym_SEMICOLON }, 33 },
   { { 30, sym_DOUBLE }, 2 }, { { 6, sym_PLUS }, 6 }, { { 19, sym_H }, 16 }, { { 10, sym_SEMICOLON }, 28 }, { { 47, sym_PLUS }, 29 },
   { { 9, sym_SEMICOLON }, 27 }, { { 6, sym_H }, 16 }, { { 17, sym_MINUS }, 30 }, { { 7, sym_H }, 16 }, { { 29, sym_DOUBLE }, 2 },
   { { 11, sym_SEMICOLON }, 31 }, { { 41, sym_PLUS }, 29 }, { { 44, sym_E }, 47 }, { { 20, sym_IDENT }, 18 }, { { 6, sym_IDENT }, 18 },
   { { 6, sym_DOUBLE }, 2 }, { { 8, sym_SEMICOLON }, 26 }, { { 40, sym_PLUS }, 29 }, { { 6, sym_G }, 24 }, { { 5, sym_LPAR }, 22 },
   { { 30, sym_G }, 14 }, { { 1, sym__recover_ }, 12 }, { { 3, sym_E }, 17 }, { { 7, sym_IDENT }, 18 }, { { 19, sym_PLUS }, 6 },
   { { 1, sym_E }, 11 }, { { 21, sym_DOUBLE }, 2 }, { { 16, sym_FACTORIAL }, 34 }, { { 29, sym_PLUS }, 6 }, { { 1, sym_Show }, 8 },
   { { 4, sym_DIVIDES }, 20 }, { { 11, sym_PLUS }, 29 }, { { 30, sym_H }, 16 }, { { 1, sym_Command }, 13 }, { { 21, sym_IDENT }, 18 },
   { { 1, sym_PLUS }, 6 }, { { 7, sym_G }, 25 }, { { 0, sym_Session }, 1 }, { { 1, sym_Debug }, 9 }, { { 4, sym_MODULO }, 19 },
   { { 1, sym_DOUBLE }, 2 }, { { 1, sym_LPAR }, 3 }, { { 4, sym_TIMES }, 21 }, { { 6, sym_LPAR }, 3 }, { { 11, sym_MINUS }, 30 },
   { { 1, sym_H }, 16 }, { { 17, sym_RPAR }, 35 }, { { 5, sym_ASSIGN }, 23 }, { { 1, sym_G }, 14 }, { { 1, sym_Quit }, 15 },
   { { 18, sym_LPAR }, 22 }, { { 3, sym_G }, 14 }, { { 29, sym_F }, 42 }, { { 17, sym_PLUS }, 29 }, { { 43, sym_DIVIDES }, 20 },
   { { 44, sym_PLUS }, 6 }, { { 22, sym_IDENT }, 18 }, { { 12, sym_SEMICOLON }, 32 }, { { 7, sym_DOUBLE }, 2 }, { { 3, sym_LPAR }, 3 },
   { { 47, sym_MINUS }, 30 }, { { 3, sym_F }, 4 }, { { 19, sym_G }, 36 }, { { 7, sym_LPAR }, 3 }, { { 3, sym_DOUBLE }, 2 },
   { { 1, sym_MINUS }, 7 }, { { 23, sym_H }, 16 }, { { 7, sym_PLUS }, 6 }, { { 19, sym_IDENT }, 18 }, { { 3, sym_H }, 16 },
   { { 21, sym_MINUS }, 7 }, { { 19, sym_DOUBLE }, 2 }, { { 7, sym_MINUS }, 7 }, { { 21, sym_H }, 16 }, { { 19, sym_LPAR }, 3 },
   { { 30, sym_F }, 43 }, { { 42, sym_DIVIDES }, 20 }, { { 6, sym_MINUS }, 7 }, { { 20, sym_H }, 16 }, { { 20, sym_MINUS }, 7 },
   { { 20, sym_DOUBLE }, 2 }, { { 29, sym_IDENT }, 18 }, { { 20, sym_LPAR }, 3 }, { { 44, sym_LPAR }, 3 }, { { 21, sym_G }, 38 },
   { { 21, sym_LPAR }, 3 }, { { 22, sym_MINUS }, 7 }, { { 23, sym_G }, 14 }, { { 22, sym_PLUS }, 6 }, { { 1, sym_Nodebug }, 10 },
   { { 22, sym_H }, 16 }, { { 22, sym_F }, 4 }, { { 22, sym_LPAR }, 3 }, { { 43, sym_MODULO }, 19 }, { { 22, sym_DOUBLE }, 2 },
   { { 22, sym_G }, 14 }, { { 23, sym_MINUS }, 7 }, { { 3, sym_IDENT }, 18 }, { { 23, sym_PLUS }, 6 }, { { 3, sym_PLUS }, 6 },
   { { 23, sym_IDENT }, 18 }, { { 23, sym_F }, 4 }, { { 1, sym_IDENT }, 5 }, { { 21, sym_PLUS }, 6 }, { { 23, sym_E }, 41 },
   { { 23, sym_LPAR }, 3 }, { { 42, sym_MODULO }, 19 }, { { 23, sym_DOUBLE }, 2 }, { { 19, sym_MINUS }, 7 }, { { 29, sym_G }, 14 },
   { { 20, sym_PLUS }, 6 }, { { 22, sym_E }, 40 }, { { 29, sym_H }, 16 }, { { 29, sym_MINUS }, 7 }, { { 29, sym_LPAR }, 3 },
   { { 30, sym_IDENT }, 18 }, { { 30, sym_MINUS }, 7 }, { { 30, sym_LPAR }, 3 }, { { 39, sym_RPAR }, 45 }, { { 30, sym_PLUS }, 6 },
   { { 39, sym_COMMA }, 44 }, { { 1, sym_F }, 4 }, { { 41, sym_MINUS }, 30 }, { { 40, sym_MINUS }, 30 }, { { 41, sym_SEMICOLON }, 46 },
   { { 42, sym_TIMES }, 21 }, { { 43, sym_TIMES }, 21 }
};

const parser::statesymbol::map< std::vector< size_t >> parser::reductions =
{
   { { 5, sym_PLUS }, { 21 } }, { { 5, sym_MINUS }, { 21 } }, { { 5, sym_TIMES }, { 21 } }, { { 5, sym_DIVIDES }, { 21 } },
   { { 5, sym_FACTORIAL }, { 21 } }, { { 5, sym_SEMICOLON }, { 26, 27, 28, 29, 21 } }, { { 5, sym_MODULO }, { 21 } }
};


const std::vector< parser::expectation > parser::errormessages =
{
   { { {{ sym_IDENT }, 0 }, {{ sym_LPAR }, 0 } }, "a function argument" },
   { { {{ sym_F }, 0 }, {{ sym_DIVIDES, sym_TIMES }, 0 } }, "a factor" }
};


