
// The code below was generated by Maphoon 2023.

// Definition of struct symbol:

#ifndef SYMBOL_
#define SYMBOL_    1

#include <iostream>
#include <variant>
#include <optional>
#include <concepts>
#include <stdexcept>

#line 43 "grammar.m"
 #include <vector> 

enum symbolval
{
   sym__recover_, sym_DIVIDES, sym_DOUBLE, sym_TIMES, 
   sym_COMMA, sym_MODULO, sym_MINUS, sym_Show, 
   sym_SEMICOLON, sym_Command, sym_WHITESPACE, sym_ASSIGN, 
   sym_BAD, sym_PLUS, sym_EOF, sym_FACTORIAL, 
   sym_Nodebug, sym_RPAR, sym_Debug, sym_IDENT, 
   sym_E, sym_EMPTY, sym_SCANERROR, sym_F, 
   sym_G, sym_H, sym_Quit, sym_Arguments, 
   sym_Session, sym_LPAR, sym_COMMENT
};

const char* getcstring( symbolval );

inline std::ostream& operator << ( std::ostream& out, symbolval val )
   { out << getcstring( val );  return out; }

struct symbol
{
   using attrtype = std::variant < std::monostate, std::string, std::vector<double>, 
         double > ;

   symbolval val;
   attrtype attr;

   symbol( ) = delete;
   symbol( const symbol& ) = default;
   symbol( symbol&& ) noexcept = default;
   symbol& operator = ( const symbol& ) = default;
   symbol& operator = ( symbol&& ) noexcept = default;
   ~symbol( ) = default;

   // Construct symbol with void attribute:

   symbol( symbolval val )
    : val( val )
   { }

   // Template constructor from const attribute& :

   template< typename _T >
      requires std::convertible_to< _T, attrtype > && std::copy_constructible< _T >
   symbol( symbolval val,
           const _T & attr )
    : val( val ),
      attr( attr )
   { }

   // Template onstructor from attribute&& :

   template< typename _T >
      requires std::convertible_to< _T, attrtype > && std::move_constructible< _T >
   symbol( symbolval val,
           _T && attr )
    : val( val ),
      attr( std::move( attr ))
   { }

   void print( std::ostream& out ) const;

   bool has_correct_attribute( ) const;

   template< typename T > T& get( )
      { return std::get<T> ( attr ); }
   
   template< typename T > const T& get( ) const
      { return std::get<T> ( attr ); }
   
};

inline
std::ostream& operator << ( std::ostream& out, const symbol& sym )
   { sym. print( out ); return out; }


#endif


